### ISSUE TITLE
API: Accept Image Size Param and Return Full Image Path In Search

### ISSUE THREAD

**Issue by LanceGundersen** [nerdtribe/mr-binge#53]
As a developer I should be able to provide an image size param in the mr. binge api search endpoint(s) and get the full image path returned in the response JSON.

## Scenario 1
A search for a movies is conducted to the broad movie request endpoint without a specified image size. _The available image sizes are listed here: https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400_

### Expected result
The response JSON should contain a full valid http path containing a default image size. `https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg`

### Actual result
The response JSON contains a poster_path property that only contains the poster id `/db32LaOibwEliAmSL2jjDF6oDdj.jpg`

## Scenario 1
A search for a movies is conducted to the broad movie request endpoint with a specified image size. _The available image sizes are listed here: https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400_

### Expected result
The response JSON should contain a full valid http path containing a default image size. `https://image.tmdb.org/t/p/w342/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg`

### Actual result
N/A as not implemented yet.

## Proposed Fix
The Mr. Binge search endpoints (Broad Movie, Broad TV, Detailed Movie and Detailed TV) all accept an optional param for poster_size that accepts a string. _The available image sizes are listed here: https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400_

**Comment by Drbaltar** [comment]
Added the full path for images (poster and backdrop) for the media entries returned from broad and detailed searches. The returned image size is defaulted to 'w500' for posters and 'w780' for backdrops. Additionally, I added two optional query parameters to set the returned poster and backdrop paths to the appropriate size. The parameters are 'posterSize' and 'backdropSize' respectively. I already deployed changes to server. Please test and close issue if the implementation fixes this issue.

**Comment by LanceGundersen** [comment]
Can confirm implementation is fixed. 🎉 
Movies No params specified
![image](https://user-images.githubusercontent.com/8315447/87314974-e6689f00-c4f1-11ea-8374-d32256b4c75b.png)
Movies Poster size param
![image](https://user-images.githubusercontent.com/8315447/87314823-c042ff00-c4f1-11ea-871b-f44047a6bf1c.png)
Movies Backdrop size param
![image](https://user-images.githubusercontent.com/8315447/87314934-d9e44680-c4f1-11ea-83bf-4c88ee4f972a.png)

TV No params specified
![image](https://user-images.githubusercontent.com/8315447/87315299-570fbb80-c4f2-11ea-9180-ccccc1488e5b.png)
TV Poster size param
![image](https://user-images.githubusercontent.com/8315447/87315261-495a3600-c4f2-11ea-92b9-119caf367931.png)
TV Backdrop size param
![image](https://user-images.githubusercontent.com/8315447/87315212-33e50c00-c4f2-11ea-9bc6-cc09ae091d3d.png)
